-- 코드를 작성해주세요
-- FISH _INFO
-- FISH_NAME_INFO

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME = 'BASS' OR FNI.FISH_NAME = 'SNAPPER'
;
